export const CONFIG = {
  canvas: { width: 960, height: 540 },
  world: {
    groundY: 455,
    gravity: 790,
    maxWind: 190,
    windJitter: 26,
    cloudSpeedNear: 18,
    cloudSpeedFar: 9
  },
  wall: {
    x: 480,
    width: 56,
    height: 132,
    maxHp: 150
  },
  aim: {
    angleMin: 12,
    angleMax: 82,
    angleSpeed: 82,
    angleTap: 1.8,
    defaultAngle: 42,
    powerMin: 310,
    powerMax: 760,
    powerSpeed: 280,
    powerTap: 18,
    defaultPower: 500
  },
  touch: {
    pickupRadius: 78,
    dragMin: 24,
    dragMax: 210,
    fireThreshold: 40,
    angleBase: 18
  },
  turn: {
    readyPause: 0.82,
    impactPause: 0.92,
    endPause: 1.25,
    healPause: 0.78,
    bossFollowUpPause: 0.42,
    heavyBurstDelay: 0.6
  },
  player: {
    maxHp: 110,
    headRadius: 17,
    bodyRadius: 24,
    handOffsetX: 34,
    handOffsetY: 63,
    idleBobAmount: 4,
    anticipationLift: 7,
    recoilAmount: 7
  },
  projectile: {
    maxStepPixels: 16,
    trailPoints: 18
  },
  particles: {
    maxLife: 0.85
  },
  projectileTypes: {
    normal: {
      label: "Normal",
      note: "Ball",
      ammo: Infinity,
      shape: "ball",
      weight: 1,
      launchSpeedMultiplier: 1.01,
      gravityMultiplier: 1.04,
      windInfluenceMultiplier: 1.22,
      radius: 7,
      damageMin: 10,
      damageMax: 27,
      directBonus: 10,
      splashRadius: 64,
      aiBias: 0,
      trailColor: "rgba(255, 245, 205, 0.35)",
      coreColor: "#f3b14c",
      ringColor: "rgba(255, 223, 143, 0.9)",
      windup: 0.17,
      recoil: 0.18,
      launchBurst: 7,
      explosionParticles: 22,
      explosionForce: 1,
      shake: 6
    },
    light: {
      label: "Light",
      note: "Burst x3",
      ammo: 2,
      shape: "stick",
      weight: 0.66,
      launchSpeedMultiplier: 1.08,
      gravityMultiplier: 0.84,
      windInfluenceMultiplier: 2.1,
      radius: 5.2,
      damageMin: 3,
      damageMax: 8,
      directDamage: 11,
      directBonus: 0,
      splashRadius: 32,
      aiBias: 1.6,
      trailColor: "rgba(212, 245, 255, 0.42)",
      coreColor: "#7fd0eb",
      ringColor: "rgba(170, 235, 255, 0.9)",
      windup: 0.12,
      recoil: 0.14,
      launchBurst: 6,
      explosionParticles: 14,
      explosionForce: 0.72,
      shake: 4.2,
      burstCount: 3,
      burstDelay: 0.11,
      burstSpread: 3.8,
      burstPowerFalloff: 0.07
    },
    heavy: {
      label: "Heavy",
      note: "Shards",
      ammo: 3,
      shape: "rock",
      weight: 1.72,
      launchSpeedMultiplier: 0.89,
      gravityMultiplier: 1.3,
      windInfluenceMultiplier: 0.46,
      radius: 9.2,
      damageMin: 14,
      damageMax: 31,
      directBonus: 14,
      splashRadius: 70,
      aiBias: 5,
      trailColor: "rgba(255, 220, 170, 0.42)",
      coreColor: "#d8783b",
      ringColor: "rgba(255, 186, 119, 0.92)",
      windup: 0.22,
      recoil: 0.24,
      launchBurst: 9,
      explosionParticles: 26,
      explosionForce: 1.18,
      shake: 8.2,
      fragmentCount: 3,
      fragmentSpeedMin: 132,
      fragmentSpeedMax: 190
    },
    super: {
      label: "Super",
      note: "Tracks late",
      ammo: 1,
      shape: "rocket",
      weight: 1.28,
      launchSpeedMultiplier: 0.92,
      gravityMultiplier: 1.2,
      windInfluenceMultiplier: 0.92,
      radius: 7,
      damageMin: 14,
      damageMax: 24,
      directDamage: 55,
      directBonus: 0,
      splashRadius: 44,
      aiBias: 10,
      trailColor: "rgba(255, 189, 168, 0.46)",
      coreColor: "#ef6b52",
      ringColor: "rgba(255, 171, 146, 0.94)",
      windup: 0.26,
      recoil: 0.3,
      launchBurst: 10,
      explosionParticles: 32,
      explosionForce: 1.34,
      shake: 9.6,
      trackingDelay: 0.5,
      trackingTurnRate: 2.35,
      trackingAcceleration: 18,
      trackingMaxSpeedMultiplier: 1.1
    }
  },
  specialProjectiles: {
    heavyShard: {
      label: "Shard",
      note: "5 dmg",
      shape: "rock",
      weight: 0.78,
      launchSpeedMultiplier: 1,
      gravityMultiplier: 1.24,
      windInfluenceMultiplier: 0.7,
      radius: 4.2,
      damageMin: 2,
      damageMax: 4,
      directDamage: 5,
      directBonus: 0,
      splashRadius: 18,
      trailColor: "rgba(255, 219, 180, 0.34)",
      coreColor: "#e29a62",
      ringColor: "rgba(255, 209, 156, 0.9)",
      explosionParticles: 8,
      explosionForce: 0.52,
      shake: 2.4,
      renderScale: 0.62,
      fragment: true
    },
    bossEcho: {
      label: "Echo",
      note: "Cheat shot",
      shape: "ball",
      weight: 0.96,
      launchSpeedMultiplier: 1,
      gravityMultiplier: 0.98,
      windInfluenceMultiplier: 1.18,
      radius: 5.6,
      damageMin: 4,
      damageMax: 9,
      directBonus: 4,
      splashRadius: 32,
      trailColor: "rgba(199, 173, 255, 0.34)",
      coreColor: "#a679ff",
      ringColor: "rgba(225, 208, 255, 0.9)",
      explosionParticles: 12,
      explosionForce: 0.72,
      shake: 3.4,
      renderScale: 0.82,
      bossOnly: true
    }
  },
  items: {
    heal: {
      label: "Heal",
      note: "Restore 35% max HP instantly",
      ammo: 1,
      healRatio: 0.35,
      icon: "heal",
      coreColor: "#6fcb87",
      ringColor: "rgba(181, 255, 196, 0.9)"
    }
  },
  cpuProfiles: {
    easy: {
      label: "Easy",
      description: "Loose read, wide misses.",
      angleStep: 3,
      powerStep: 18,
      topChoices: 12,
      choiceSpread: 7,
      angleJitter: 6.2,
      powerJitter: 40,
      delayMin: 1.1,
      delayMax: 1.7,
      scoreBias: 1.16
    },
    normal: {
      label: "Normal",
      description: "Solid read, believable mistakes.",
      angleStep: 2,
      powerStep: 12,
      topChoices: 8,
      choiceSpread: 4,
      angleJitter: 3.8,
      powerJitter: 24,
      delayMin: 0.9,
      delayMax: 1.35,
      scoreBias: 1.04
    },
    hard: {
      label: "Hard",
      description: "Sharper reads, small mistakes.",
      angleStep: 1,
      powerStep: 8,
      topChoices: 4,
      choiceSpread: 2,
      angleJitter: 2.2,
      powerJitter: 14,
      delayMin: 0.55,
      delayMax: 0.92,
      scoreBias: 0.9
    },
    impossible: {
      label: "Impossible",
      description: "Cheats shamelessly. Good luck.",
      angleStep: 1,
      powerStep: 6,
      topChoices: 3,
      choiceSpread: 1,
      angleJitter: 1.1,
      powerJitter: 8,
      delayMin: 0.38,
      delayMax: 0.62,
      scoreBias: 0.72,
      doubleShotChance: 0.48,
      echoShotChance: 0.36,
      fullHealThreshold: 0.7
    }
  }
};
