export const CONFIG = {
  canvas: { width: 960, height: 540 },
  world: {
    groundY: 455,
    gravity: 790,
    maxWind: 152,
    windJitter: 20,
    cloudSpeedNear: 18,
    cloudSpeedFar: 9
  },
  aim: {
    angleMin: 12,
    angleMax: 82,
    angleSpeed: 82,
    angleTap: 1.8,
    defaultAngle: 42,
    powerMin: 310,
    powerMax: 760,
    powerSpeed: 280,
    powerTap: 18,
    defaultPower: 500
  },
  touch: {
    pickupRadius: 78,
    dragMin: 24,
    dragMax: 210,
    fireThreshold: 40,
    angleBase: 18
  },
  turn: {
    readyPause: 0.82,
    impactPause: 0.92,
    endPause: 1.25,
    healPause: 0.78
  },
  player: {
    maxHp: 110,
    headRadius: 17,
    bodyRadius: 24,
    handOffsetX: 34,
    handOffsetY: 63,
    idleBobAmount: 4,
    anticipationLift: 7,
    recoilAmount: 7
  },
  projectile: {
    maxStepPixels: 16,
    trailPoints: 18
  },
  particles: {
    maxLife: 0.85
  },
  projectileTypes: {
    normal: {
      label: "Normal",
      note: "Balanced ball with reliable reach",
      ammo: Infinity,
      shape: "ball",
      launchSpeedMultiplier: 1.16,
      gravityMultiplier: 1,
      windInfluenceMultiplier: 1.08,
      radius: 7,
      damageMin: 10,
      damageMax: 27,
      directBonus: 10,
      splashRadius: 66,
      aiBias: 0,
      trailColor: "rgba(255, 245, 205, 0.35)",
      coreColor: "#f3b14c",
      ringColor: "rgba(255, 223, 143, 0.9)",
      windup: 0.17,
      recoil: 0.18,
      launchBurst: 7,
      explosionParticles: 22,
      explosionForce: 1,
      shake: 6
    },
    light: {
      label: "Light",
      note: "Fast stick with flatter travel",
      ammo: 5,
      shape: "stick",
      launchSpeedMultiplier: 1.18,
      gravityMultiplier: 0.84,
      windInfluenceMultiplier: 1.34,
      radius: 5.4,
      damageMin: 6,
      damageMax: 16,
      directBonus: 6,
      splashRadius: 50,
      aiBias: 1.2,
      trailColor: "rgba(212, 245, 255, 0.42)",
      coreColor: "#7fd0eb",
      ringColor: "rgba(170, 235, 255, 0.9)",
      windup: 0.12,
      recoil: 0.14,
      launchBurst: 6,
      explosionParticles: 16,
      explosionForce: 0.78,
      shake: 4.5
    },
    heavy: {
      label: "Heavy",
      note: "Dense rock with harder punch",
      ammo: 3,
      shape: "rock",
      launchSpeedMultiplier: 1.1,
      gravityMultiplier: 1.12,
      windInfluenceMultiplier: 0.72,
      radius: 9.2,
      damageMin: 14,
      damageMax: 33,
      directBonus: 14,
      splashRadius: 74,
      aiBias: 4.5,
      trailColor: "rgba(255, 220, 170, 0.42)",
      coreColor: "#d8783b",
      ringColor: "rgba(255, 186, 119, 0.92)",
      windup: 0.22,
      recoil: 0.24,
      launchBurst: 9,
      explosionParticles: 28,
      explosionForce: 1.26,
      shake: 8.5
    },
    super: {
      label: "Super",
      note: "Rocket with brutal payoff",
      ammo: 1,
      shape: "rocket",
      launchSpeedMultiplier: 1.01,
      gravityMultiplier: 1.28,
      windInfluenceMultiplier: 1.18,
      radius: 7,
      damageMin: 14,
      damageMax: 24,
      directDamage: 55,
      directBonus: 0,
      splashRadius: 46,
      aiBias: 10,
      trailColor: "rgba(255, 189, 168, 0.46)",
      coreColor: "#ef6b52",
      ringColor: "rgba(255, 171, 146, 0.94)",
      windup: 0.26,
      recoil: 0.3,
      launchBurst: 10,
      explosionParticles: 32,
      explosionForce: 1.34,
      shake: 9.6
    }
  },
  items: {
    heal: {
      label: "Heal",
      note: "Restore 35% max HP instantly",
      ammo: 1,
      healRatio: 0.35,
      icon: "heal",
      coreColor: "#6fcb87",
      ringColor: "rgba(181, 255, 196, 0.9)"
    }
  },
  cpuProfiles: {
    easy: {
      label: "Easy",
      description: "Forgiving aim, slower throws, and wider misses.",
      angleStep: 3,
      powerStep: 18,
      topChoices: 12,
      choiceSpread: 7,
      angleJitter: 5.8,
      powerJitter: 36,
      delayMin: 1.1,
      delayMax: 1.7,
      scoreBias: 1.15
    },
    normal: {
      label: "Normal",
      description: "Solid reads with believable mistakes under pressure.",
      angleStep: 2,
      powerStep: 12,
      topChoices: 8,
      choiceSpread: 4,
      angleJitter: 3.2,
      powerJitter: 20,
      delayMin: 0.9,
      delayMax: 1.35,
      scoreBias: 1
    },
    hard: {
      label: "Hard",
      description: "Sharper decisions, faster releases, and tighter corrections.",
      angleStep: 1,
      powerStep: 8,
      topChoices: 4,
      choiceSpread: 2,
      angleJitter: 1.7,
      powerJitter: 10,
      delayMin: 0.55,
      delayMax: 0.92,
      scoreBias: 0.84
    }
  }
};
